# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
    push:
    pull_request:
        branches: [main]
jobs:
    basic-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 24.x
              uses: actions/setup-node@v5
              with:
                  node-version: 24.x
                  cache: 'npm'
            - run: npm ci
            - run: make lunr.js
            - run: make lint
            - run: make test
    bencher:
        runs-on: ubuntu-latest
        needs: basic-checks
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 24.x
              uses: actions/setup-node@v5
              with:
                  node-version: 24.x
                  cache: 'npm'
            - run: npm ci
            - run: make lunr.js
            - uses: bencherdev/bencher@main
            - run: |
                bencher run \
                --project satisfactory-dev-lunr-fork \
                --token '${{ secrets.BENCHER_API_TOKEN }}' \
                --err \
                --adapter json \
                node ./perf/perf_runner.ts
    coverage:
        if: github.event.repository.visibility == 'public'
        needs: basic-checks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 24.x
              uses: actions/setup-node@v5
              with:
                  node-version: 24.x
                  cache: 'npm'
            - run: npm ci
            - run: make lunr.js
            - name: Generate coverage
              run: ./node_modules/.bin/c8 --config=./.c8rc.coveralls.json make test
            - name: Coveralls GitHub Action
              uses: coverallsapp/github-action@v2.2.3
              with:
                  file: './coverage/lcov.info'
